language: android
dist: bionic
android:
  components:
    - build-tools-29.0.3
    - android-28
addons:
  apt:
    packages:
      - npmjs
install:
  - npm install
  - bundle install
script:
  - fastlane android ci