module.exports=
[
   {
      "name":"Summerdemo",
      "bpm":100,
      "key":"HxwY6vaPh",
      "musicKey":"G",
      "minor":true,
      "layers":[
         {
            "key":"dUG8FJ4pN",
            "instrumentName":"Drum",
            "audible":true,
            "volume":1,
            "seq":[
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[7],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[5],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[7],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[7],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[8],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[5],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[7],
                  "vel":0.25,
                  "stacc":false
               }
            ],
            "index":"0"
         },
         {
            "key":"JPsgSsHBe",
            "instrumentName":"String Bass",
            "audible":true,
            "volume":1,
            "seq":[
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[2],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"1"
         },
         {
            "key":"cwYIn2xpD",
            "instrumentName":"Piano",
            "audible":true,
            "volume":0.15,
            "seq":[
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[3,4,5],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[3,4,5],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[3,4,5],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[3,4,5],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"2"
         },
         {
            "key":"bW6UZfFVS",
            "instrumentName":"Korg Organ",
            "audible":true,
            "volume":0.44,
            "seq":[
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[3,4,5],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"3"
         },
         {
            "key":"P_3HCSjAg",
            "instrumentName":"Clav",
            "audible":true,
            "volume":0.69,
            "seq":[
               {
                  "sounds":[],
                  "vel":0.25,
                  "stacc":true
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[1],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[2],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[0],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"4"
         },
         {
            "key":"CJAtgzqly",
            "instrumentName":"Piano",
            "audible":true,
            "volume":0.11,
            "seq":[
               {
                  "sounds":[6,7,8],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[6,7,8],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":0.5,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               },
               {
                  "sounds":[
                     6,
                     7,
                     8
                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":true
               }
            ],
            "index":"5"
         }
      ],
      "chordSequence":[
         {
            "chordIndex":0,
            "key":"Mjh3GYwkZg"
         }
      ],
      "sections":[
         [
            0,
            0,
            4,
            0,
            3,
            3,
            4,
            4
         ],
         [
            2,
            6,
            5,
            0
         ],
         [
            0,
            0,
            0,
            0,
            3,
            3,
            0,
            0,
            4,
            3,
            0,
            0
         ]
      ]
   },
   {
      "name":"Boystrings",
      "bpm":100,
      "key":"KPc5mxeRG",
      "musicKey":"C",
      "minor":false,
      "layers":[
         {
            "key":"iAfBtVAkb",
            "instrumentName":"Strings",
            "audible":true,
            "volume":0.13,
            "seq":[
               {
                  "sounds":[
                     0,
                     1,
                     2
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"0"
         },
         {
            "key":"8gIRU6JI9",
            "instrumentName":"String Bass",
            "audible":true,
            "volume":1,
            "seq":[
               {
                  "sounds":[
                     3
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     2
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     1
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"1"
         },
         {
            "key":"JHQZbxqXH",
            "instrumentName":"Piano",
            "audible":true,
            "volume":0.25,
            "seq":[
               {
                  "sounds":[
                     0,
                     1,
                     2
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"2"
         },
         {
            "key":"uRJpZq3so",
            "instrumentName":"Drums",
            "audible":true,
            "volume":1,
            "seq":[
               {
                  "sounds":[
                     5,
                     0
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     4
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     7
                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     4,
                     0
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     7
                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     5
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     5,
                     0
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     7
                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     4
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     4,
                     0
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":0.25,
                  "stacc":false
               },
               {
                  "sounds":[
                     5
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     7
                  ],
                  "vel":0.25,
                  "stacc":false
               }
            ],
            "index":"3"
         },
         {
            "key":"CjO5tRooZ",
            "instrumentName":"Piano",
            "audible":true,
            "volume":0.25,
            "seq":[
               {
                  "sounds":[
                     0
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     1
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     2
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[
                     3
                  ],
                  "vel":1,
                  "stacc":false
               },
               {
                  "sounds":[

                  ],
                  "vel":1,
                  "stacc":false
               }
            ],
            "index":"4"
         }
      ],
      "chordSequence":[
         {
            "chordIndex":0,
            "key":"AkyQvxnl8o"
         }
      ],
      "sections":[
         [
            0,
            4,
            3,
            5
         ],
         [
            0
         ],
         [
            0
         ]
      ]
   }
]
;