platform :ios do
  desc "Build ios"
  lane :master do
    import_certificate(
      certificate_path: 'cert/ios_distribution.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: 'build.keychain',
      keychain_password: 'nosecret'
    )
    install_provisioning_profile(
      path: 'cert/Hoodmode_AdHoc_200525.mobileprovision'
    )
    cordova(
      type: 'adhoc',
      platform: 'ios',
      team_id: 'UAWAHU68LH',
      provisioning_profile: '4412c129-1bf8-4ca1-ab11-759ff00b1700'
    )
    applivery(
      app_token: ENV['APPLIVERY_TOKEN'],
      build_path: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH']
    )
  end

  lane :alpha do
    import_certificate(
      certificate_path: 'cert/ios_distribution.p12',
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: 'build.keychain',
      keychain_password: 'nosecret'
    )
    install_provisioning_profile(
      path: 'cert/Hoodmode_AppStore_200525.mobileprovision'
    )
    cordova(
      type: 'appstore',
      platform: 'ios',
      team_id: 'UAWAHU68LH',
      provisioning_profile: '0cb6686b-1a84-495f-b783-2f4a6bd11a41'
    )
#    upload_to_app_store(
#      username: "li.mikael@gmail.com",
#      ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],
#      skip_metadata: true,
#      skip_screenshots: true,
#      skip_app_version_update: true
#    )
    altool(
      altool_username: 'li.mikael@gmail.com',
      altool_password: ENV['APPLE_APP_PASSWORD'],
      altool_app_type: 'ios',
      altool_ipa_path: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'],
      altool_output_format: 'xml'
    )
  end
end

platform :android do
  desc "Build Android version"
  lane :local do
    cordova(
      platform: 'android',
      keystore_path: 'cert/hoodmode-micke.keystore',
      keystore_alias: 'hoodmode-micke',
      keystore_password: ENV["KEYSTORE_PASSWORD"]
    )
  end

  lane :master do
    cordova(
      platform: 'android',
      keystore_path: 'cert/hoodmode-micke.keystore',
      keystore_alias: 'hoodmode-micke',
      keystore_password: ENV["KEYSTORE_PASSWORD"]
    )
    applivery(
      app_token: ENV["APPLIVERY_TOKEN"],
      build_path: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH']
    )
  end

  lane :alpha do
    cordova(
      platform: 'android',
      keystore_path: 'cert/hoodmode-micke.keystore',
      keystore_alias: 'hoodmode-micke',
      keystore_password: ENV["KEYSTORE_PASSWORD"]
    )
    upload_to_play_store(
      package_name: 'app.hoodmode.co',
      track: 'alpha',
      apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'],
      json_key: 'cert/api-8205799664942222636-981263-fe8ee5d9f8f0.json'
    )
  end
end